In [ ]:
import pandas as pd
import numpy as np

# Veri setini oluşturma
np.random.seed(42)

# Veri özellikleri
n_samples = 223  # rastgele bir veri sayısı verdim

# Yaş (18-65 arası)
ages = np.random.randint(18, 65, n_samples)

# Gelir (Düşük, Orta, Yüksek)
income = np.random.choice(['Low', 'Medium', 'High'], n_samples)

# Medeni Durum (Evli, Bekar)
marital_status = np.random.choice(['Single', 'Married'], n_samples)

# Eğitim Durumu (Lise, Üniversite)
education = np.random.choice(['High School', 'University'], n_samples)

# Kredi Geçmişi (İyi, Kötü)
credit_history = np.random.choice(['Good', 'Bad'], n_samples)

# Mevcut Borçlar (0-5000 arasında)
existing_debt = np.random.randint(0, 5000, n_samples)

# Kredi Onayı (Hedef: 0 veya 1)
# Burada kredi onayını gelire,kredi geçmişine ve kredi borcuna göre biraz şekillendireceğiz
# Bu özellikler diğer özelliklere göre bi tık daha ön planda olacak tahminleme sırasında
credit_approval = []

for i in range(n_samples):
    # Yüksek geliri olan ve iyi kredi geçmişine sahip kişilerin kredi alması daha olası
    if income[i] == 'High' and credit_history[i] == 'Good':
        credit_approval.append(1)
    # Orta geliri olan ve iyi kredi geçmişi olanlar da kredi alabilir
    elif income[i] == 'Medium' and credit_history[i] == 'Good':
        credit_approval.append(np.random.choice([0, 1], p=[0.3, 0.7]))  # %70 kredi onayı
    # Kötü kredi geçmişi olanlar genellikle kredi almaz
    elif credit_history[i] == 'Bad' and  income[i] == 'Low':
        credit_approval.append(0)
    elif credit_history[i] == 'Bad' and  existing_debt[i] > 4000:
        credit_approval.append(0)
    else:
        credit_approval.append(np.random.choice([0, 1], p=[0.5, 0.5]))  # Eşit ihtimalle karar

# Veri çerçevesini oluşturma
data = {
    'Age': ages,
    'Income': income,
    'Marital Status': marital_status,
    'Education': education,
    'Credit History': credit_history,
    'Existing Debt': existing_debt,
    'Credit Approval': credit_approval
}

df = pd.DataFrame(data)

# CSV dosyasına kaydetme
df.to_csv('veri.csv', index=False)

# İlk birkaç satırı görüntüleme
df.head()

,Age,Income,Marital Status,Education,Credit History,Existing Debt,Credit Approval
0,56,High,Single,University,Bad,4007,0
1,46,Medium,Married,High School,Bad,2472,1
2,32,Low,Married,University,Good,2660,0
3,60,Medium,Married,University,Good,2739,1
4,25,Medium,Married,University,Bad,1761,0